module.exports = {
  DISABLE_V8_COMPILE_CACHE: process.env.DISABLE_V8_COMPILE_CACHE,
  NEXT_PUBLIC_FRONTEND_URL: process.env.NEXT_PUBLIC_FRONTEND_URL,
  NEXT_PUBLIC_BACKEND_URL: process.env.NEXT_PUBLIC_BACKEND_URL
}
